### ISSUE TITLE
Support a newer OS in a docker

### ISSUE THREAD

**Issue by oleg68** [FoundationDB/fdb-joshua#32]
Now the supplied Dockerfile uses CentOs 7 as a base OS. 

This OS is quite old and it has glibc 2.17.

It is too difficult to build FoundationDb compatible with such old glibc. For example, the oldest OS supported by the GitHub action runners is Ubuntu 18.04 with glibc 2.27. So the correctness package build on GitHub cannot run in еру joshua container.

I've adopted the supplied DockerFile for CentOs 8. This os comes with glibc 2.28 and can run the correctness package build on GitHub.

I'd like to add 
[centos8.zip](https://github.com/FoundationDB/fdb-joshua/files/6821754/centos8.zip)
to the joshua repository. Is it possible? If so, I'll open a PR,

**Comment by jzhou77** [comment]
https://github.com/FoundationDB/fdb-joshua/pull/103 changed the base image to Rocky Linux 9.3
